#!/bin/bash

function createHospitals() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hospitals.healthcare.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-hospitals --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospitals.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospitals.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospitals.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospitals.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hospitals's CA cert to hospitals's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/tlscacerts/ca.crt"

  # Copy hospitals's CA cert to hospitals's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/tlsca/tlsca.hospitals.healthcare.com-cert.pem"

  # Copy hospitals's CA cert to hospitals's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/ca"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/ca/ca.hospitals.healthcare.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name hospitalsadmin --id.secret adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls" --enrollment.profile tls --csr.hosts peer0.hospitals.healthcare.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/peers/peer0.hospitals.healthcare.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/users/User1@hospitals.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/users/User1@hospitals.healthcare.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://hospitalsadmin:hospitalsadminpw@localhost:7054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/users/Admin@hospitals.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.healthcare.com/users/Admin@hospitals.healthcare.com/msp/config.yaml"
}

function createLabs() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/labs.healthcare.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/labs.healthcare.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-labs --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-labs.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-labs.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-labs.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-labs.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy labs's CA cert to labs's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/labs/ca-cert.pem" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/tlscacerts/ca.crt"

  # Copy labs's CA cert to labs's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/labs.healthcare.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/labs/ca-cert.pem" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/tlsca/tlsca.labs.healthcare.com-cert.pem"

  # Copy labs's CA cert to labs's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/labs.healthcare.com/ca"
  cp "${PWD}/organizations/fabric-ca/labs/ca-cert.pem" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/ca/ca.labs.healthcare.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-labs --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-labs --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-labs --id.name labsadmin --id.secret labsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-labs -M "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-labs -M "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls" --enrollment.profile tls --csr.hosts peer0.labs.healthcare.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/labs.healthcare.com/peers/peer0.labs.healthcare.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-labs -M "${PWD}/organizations/peerOrganizations/labs.healthcare.com/users/User1@labs.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/users/User1@labs.healthcare.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://labsadmin:labsadminpw@localhost:8054 --caname ca-labs -M "${PWD}/organizations/peerOrganizations/labs.healthcare.com/users/Admin@labs.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/labs/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/labs.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/labs.healthcare.com/users/Admin@labs.healthcare.com/msp/config.yaml"
}


function createInsurancecompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/insurancecompany.healthcare.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-insurancecompany --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurancecompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurancecompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurancecompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurancecompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy insurancecompany's CA cert to insurancecompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/tlscacerts/ca.crt"

  # Copy insurancecompany's CA cert to insurancecompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/tlsca/tlsca.insurancecompany.healthcare.com-cert.pem"

  # Copy insurancecompany's CA cert to insurancecompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/ca"
  cp "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/ca/ca.insurancecompany.healthcare.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-insurancecompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-insurancecompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-insurancecompany --id.name insurancecompanyadmin --id.secret insurancecompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-insurancecompany -M "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-insurancecompany -M "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls" --enrollment.profile tls --csr.hosts peer0.insurancecompany.healthcare.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/peers/peer0.insurancecompany.healthcare.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-insurancecompany -M "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/users/User1@insurancecompany.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/users/User1@insurancecompany.healthcare.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://insurancecompanyadmin:insurancecompanyadminpw@localhost:11054 --caname ca-insurancecompany -M "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/users/Admin@insurancecompany.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurancecompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurancecompany.healthcare.com/users/Admin@insurancecompany.healthcare.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/healthcare.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/healthcare.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/healthcare.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthcare.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/healthcare.com/msp/tlscacerts/tlsca.healthcare.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthcare.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/healthcare.com/tlsca/tlsca.healthcare.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls" --enrollment.profile tls --csr.hosts orderer.healthcare.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp/tlscacerts/tlsca.healthcare.com-cert.pem"

  echo "Generating the admin msp"
  set -x

  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthcare.com/users/Admin@healthcare.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/healthcare.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/healthcare.com/users/Admin@healthcare.com/msp/config.yaml"
}

createHospitals
createLabs
createInsurancecompany
createOrderer